site: boch.dev
url: 'https://boch.dev'
title: boch.dev
description: Dull notes about Ruby and JS.
twitter:
  username: Boch_Patryk
  card: summary
  creator: patrykboch
author:
  twitter: patrykboch
  name: Patryk
  avatar:
  email: patrykboch@gmail.com
  url: boch.dev
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"